language: ruby
cache: bundler
python: 3.7
before_install:
  - yes | gem update --system --force
  - gem install bundle
addons:
  apt_packages:
      - pandoc
branches:
  only:
  - dev
script:
  - make html
deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev
