language: ruby
cache: bundler
before_install:
  - yes | gem update --system --force
  - gem install bundler
addons:
  apt_packages:
      - pandoc
branches:
  only:
  - master
script:
  - make html
deploy:
  provider: pages
  local-dir: ./site
  target-branch: release
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
