jobs:
  exclude:
    - rvm: 2.5.3
      gemfile: Gemfile

branches:
  only:
  - dev
deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev
